# Generated by Django 4.0 on 2025-04-30 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_number_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
